//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dokana.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dokana.Resources.ResourceKeys", typeof(ResourceKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Password.
        /// </summary>
        public static string accountPassword {
            get {
                return ResourceManager.GetString("accountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Photo.
        /// </summary>
        public static string accountPhoto {
            get {
                return ResourceManager.GetString("accountPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #إنترنت_غير_محدود_في_مصر.
        /// </summary>
        public static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cant add your review 2 times.
        /// </summary>
        public static string add2reviewsMsg {
            get {
                return ResourceManager.GetString("add2reviewsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Phone Number.
        /// </summary>
        public static string addPhoneNumber {
            get {
                return ResourceManager.GetString("addPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abu tesht, Qena, Egypt.
        /// </summary>
        public static string addressOfCompany {
            get {
                return ResourceManager.GetString("addressOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Admins.
        /// </summary>
        public static string addToAdmins {
            get {
                return ResourceManager.GetString("addToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorite.
        /// </summary>
        public static string addToFavorite {
            get {
                return ResourceManager.GetString("addToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Sellers.
        /// </summary>
        public static string addToSellers {
            get {
                return ResourceManager.GetString("addToSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Shipping Staff.
        /// </summary>
        public static string addToShippingStaff {
            get {
                return ResourceManager.GetString("addToShippingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Super Admins.
        /// </summary>
        public static string addToSuperAdmins {
            get {
                return ResourceManager.GetString("addToSuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Add Your ad Here.
        /// </summary>
        public static string addYourAd {
            get {
                return ResourceManager.GetString("addYourAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string admins {
            get {
                return ResourceManager.GetString("admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string allProducts {
            get {
                return ResourceManager.GetString("allProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Kushk company we have a team of shipping stuff they working so hard to get your products in time.
        /// </summary>
        public static string allProductsDescription {
            get {
                return ResourceManager.GetString("allProductsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you cant order any of this products at now because they are not available.
        /// </summary>
        public static string allProductsNotAvailableMsg {
            get {
                return ResourceManager.GetString("allProductsNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users On the site.
        /// </summary>
        public static string allUsersInSite {
            get {
                return ResourceManager.GetString("allUsersInSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopping cart project created with asp.net mvc 5.
        /// </summary>
        public static string appMetaDescription {
            get {
                return ResourceManager.GetString("appMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kushk.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available To Sale.
        /// </summary>
        public static string availableToSale {
            get {
                return ResourceManager.GetString("availableToSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller Products.
        /// </summary>
        public static string bestSellerProducts {
            get {
                return ResourceManager.GetString("bestSellerProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Order Level.
        /// </summary>
        public static string byOrderLevel {
            get {
                return ResourceManager.GetString("byOrderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string cancelOrder {
            get {
                return ResourceManager.GetString("cancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want to cancel this order all you need is just to press the &quot;cancel order&quot; button.
        /// </summary>
        public static string cancelOrderInfoMsg {
            get {
                return ResourceManager.GetString("cancelOrderInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order is cancled successfully.
        /// </summary>
        public static string cancelOrderMsg {
            get {
                return ResourceManager.GetString("cancelOrderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry you can not cancel this order now cause you finish all steps to checkout.
        /// </summary>
        public static string cancelOrderMsgNo {
            get {
                return ResourceManager.GetString("cancelOrderMsgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string cart {
            get {
                return ResourceManager.GetString("cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Items.
        /// </summary>
        public static string cartItems {
            get {
                return ResourceManager.GetString("cartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash On Delivary.
        /// </summary>
        public static string cashOnDelivary {
            get {
                return ResourceManager.GetString("cashOnDelivary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash OnDeliva ryD escription.
        /// </summary>
        public static string cashOnDelivaryDescription {
            get {
                return ResourceManager.GetString("cashOnDelivaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash On Delivary Fee.
        /// </summary>
        public static string cashOnDelivaryFee {
            get {
                return ResourceManager.GetString("cashOnDelivaryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is all about cash on delivary Fee .
        /// </summary>
        public static string cashOnDelivaryFeeFormMsg {
            get {
                return ResourceManager.GetString("cashOnDelivaryFeeFormMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Category Description here.
        /// </summary>
        public static string categoryDescriptionPlacholder {
            get {
                return ResourceManager.GetString("categoryDescriptionPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Category Name here.
        /// </summary>
        public static string categoryNamePlacholder {
            get {
                return ResourceManager.GetString("categoryNamePlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here you can change main site languages.
        /// </summary>
        public static string changeLanguageMsg {
            get {
                return ResourceManager.GetString("changeLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changePassword.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap.
        /// </summary>
        public static string cheap {
            get {
                return ResourceManager.GetString("cheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Kushk company we have a team of shipping stuff they working so hard to get your products in time.
        /// </summary>
        public static string cheapDescription {
            get {
                return ResourceManager.GetString("cheapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we dont support this image format you need to use this format onlay {png, jpg, jpeg}.
        /// </summary>
        public static string chooseAnotherImageErrMsg {
            get {
                return ResourceManager.GetString("chooseAnotherImageErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Payment Method.
        /// </summary>
        public static string choosePaymentMethod {
            get {
                return ResourceManager.GetString("choosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should choose product image first.
        /// </summary>
        public static string chooseProductImageErrMsg {
            get {
                return ResourceManager.GetString("chooseProductImageErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product Photo.
        /// </summary>
        public static string chooseProductPhoto {
            get {
                return ResourceManager.GetString("chooseProductPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string clickHereToLogIn {
            get {
                return ResourceManager.GetString("clickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string confirmed {
            get {
                return ResourceManager.GetString("confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string confirmEmail {
            get {
                return ResourceManager.GetString("confirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email State.
        /// </summary>
        public static string confirmEmailState {
            get {
                return ResourceManager.GetString("confirmEmailState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Order.
        /// </summary>
        public static string confirmOrder {
            get {
                return ResourceManager.GetString("confirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string confirmPasswordErrMsg {
            get {
                return ResourceManager.GetString("confirmPasswordErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Phone State.
        /// </summary>
        public static string confirmPhoneState {
            get {
                return ResourceManager.GetString("confirmPhoneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with us.
        /// </summary>
        public static string contactWithUs {
            get {
                return ResourceManager.GetString("contactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string controlPanel {
            get {
                return ResourceManager.GetString("controlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Of Products.
        /// </summary>
        public static string countOfProducts {
            get {
                return ResourceManager.GetString("countOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Order.
        /// </summary>
        public static string createAnOrder {
            get {
                return ResourceManager.GetString("createAnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        public static string createOrder {
            get {
                return ResourceManager.GetString("createOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string currentPassword {
            get {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Done.
        /// </summary>
        public static string dateOfDone {
            get {
                return ResourceManager.GetString("dateOfDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string delivered {
            get {
                return ResourceManager.GetString("delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Order.
        /// </summary>
        public static string deliveredOrder {
            get {
                return ResourceManager.GetString("deliveredOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farouk Abdelhamid.
        /// </summary>
        public static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed &amp; developed with ❤️ by.
        /// </summary>
        public static string developerCopyrights {
            get {
                return ResourceManager.GetString("developerCopyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kushk@help.com.
        /// </summary>
        public static string emailOfCompany {
            get {
                return ResourceManager.GetString("emailOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, there is a problem please try again.
        /// </summary>
        public static string errMsg {
            get {
                return ResourceManager.GetString("errMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be between 0 and 500..
        /// </summary>
        public static string errRange0_100 {
            get {
                return ResourceManager.GetString("errRange0_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Shipping.
        /// </summary>
        public static string fastShipping {
            get {
                return ResourceManager.GetString("fastShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Kushk company we have a team of shipping stuff they working so hard to get your products in time.
        /// </summary>
        public static string fastShippingDescription {
            get {
                return ResourceManager.GetString("fastShippingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string forgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("forgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string forgotPasswordMsg {
            get {
                return ResourceManager.GetString("forgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string forgotYourPassword {
            get {
                return ResourceManager.GetString("forgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All.
        /// </summary>
        public static string getAll {
            get {
                return ResourceManager.GetString("getAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Details.
        /// </summary>
        public static string goToDetails {
            get {
                return ResourceManager.GetString("goToDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Product.
        /// </summary>
        public static string goToProduct {
            get {
                return ResourceManager.GetString("goToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string grandTotal {
            get {
                return ResourceManager.GetString("grandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already have an account.
        /// </summary>
        public static string haveAccountMsg {
            get {
                return ResourceManager.GetString("haveAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Arabic.
        /// </summary>
        public static string inArabic {
            get {
                return ResourceManager.GetString("inArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In English.
        /// </summary>
        public static string inEnglish {
            get {
                return ResourceManager.GetString("inEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Done.
        /// </summary>
        public static string isDone {
            get {
                return ResourceManager.GetString("isDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Paid.
        /// </summary>
        public static string IsNotPaid {
            get {
                return ResourceManager.GetString("IsNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Signed Users.
        /// </summary>
        public static string lastSignedUsers {
            get {
                return ResourceManager.GetString("lastSignedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Products Added.
        /// </summary>
        public static string latestProductsAdded {
            get {
                return ResourceManager.GetString("latestProductsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in email or password..
        /// </summary>
        public static string loginErrorMsg {
            get {
                return ResourceManager.GetString("loginErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Currency.
        /// </summary>
        public static string mainCurrency {
            get {
                return ResourceManager.GetString("mainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is all about Main Currency.
        /// </summary>
        public static string mainCurrencyFormMsg {
            get {
                return ResourceManager.GetString("mainCurrencyFormMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your chars should be more than 250 char.
        /// </summary>
        public static string min250 {
            get {
                return ResourceManager.GetString("min250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string mobilePhone {
            get {
                return ResourceManager.GetString("mobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More About Address.
        /// </summary>
        public static string moreAboutAddress {
            get {
                return ResourceManager.GetString("moreAboutAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Items Like This.
        /// </summary>
        public static string moreItemsLikeThis {
            get {
                return ResourceManager.GetString("moreItemsLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Products.
        /// </summary>
        public static string moreProducts {
            get {
                return ResourceManager.GetString("moreProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is not Compeleted you need to Chekout using one of our payment methods.
        /// </summary>
        public static string msg4unCompeletedOrder {
            get {
                return ResourceManager.GetString("msg4unCompeletedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Aaccount.
        /// </summary>
        public static string myAaccount {
            get {
                return ResourceManager.GetString("myAaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorites.
        /// </summary>
        public static string myFavorites {
            get {
                return ResourceManager.GetString("myFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string myOrders {
            get {
                return ResourceManager.GetString("myOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string newCategory {
            get {
                return ResourceManager.GetString("newCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer.
        /// </summary>
        public static string newer {
            get {
                return ResourceManager.GetString("newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        public static string newProduct {
            get {
                return ResourceManager.GetString("newProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Shopping and choose your items.
        /// </summary>
        public static string noItemsInCartMsg {
            get {
                return ResourceManager.GetString("noItemsInCartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Phone Number.
        /// </summary>
        public static string noPhoneNumber {
            get {
                return ResourceManager.GetString("noPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry you cant add this product to your cart because is not available to sale at now..
        /// </summary>
        public static string notAvailableMsg {
            get {
                return ResourceManager.GetString("notAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confirmed.
        /// </summary>
        public static string notConfirmed {
            get {
                return ResourceManager.GetString("notConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this Order not paid.
        /// </summary>
        public static string notPaidOrder {
            get {
                return ResourceManager.GetString("notPaidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when pay the Order, levels of order going to shown here .
        /// </summary>
        public static string notPaidOrderMsg {
            get {
                return ResourceManager.GetString("notPaidOrderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is not a valid e-mail address..
        /// </summary>
        public static string notValidEmailAddressMsg {
            get {
                return ResourceManager.GetString("notValidEmailAddressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number field is not a valid phone number..
        /// </summary>
        public static string notValidPhoneNumberMsg {
            get {
                return ResourceManager.GetString("notValidPhoneNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odered at.
        /// </summary>
        public static string oderedAt {
            get {
                return ResourceManager.GetString("oderedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string older {
            get {
                return ResourceManager.GetString("older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered By.
        /// </summary>
        public static string orderedBy {
            get {
                return ResourceManager.GetString("orderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered in.
        /// </summary>
        public static string orderedIn {
            get {
                return ResourceManager.GetString("orderedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered To.
        /// </summary>
        public static string orderedTo {
            get {
                return ResourceManager.GetString("orderedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is Confirmed.
        /// </summary>
        public static string orderIsConfirmed {
            get {
                return ResourceManager.GetString("orderIsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is Delivered.
        /// </summary>
        public static string orderIsDelivered {
            get {
                return ResourceManager.GetString("orderIsDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is Shipping.
        /// </summary>
        public static string orderIsShipping {
            get {
                return ResourceManager.GetString("orderIsShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Levels.
        /// </summary>
        public static string orderLevels {
            get {
                return ResourceManager.GetString("orderLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when level is done it`s color going to be GREEN.
        /// </summary>
        public static string orderLevelsInfo {
            get {
                return ResourceManager.GetString("orderLevelsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MinimumLength must be at least 6 characters long, maximum 100.
        /// </summary>
        public static string passwordErrMsgStringLength {
            get {
                return ResourceManager.GetString("passwordErrMsgStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string paymentMethod {
            get {
                return ResourceManager.GetString("paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string paypal {
            get {
                return ResourceManager.GetString("paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paypalDescription.
        /// </summary>
        public static string paypalDescription {
            get {
                return ResourceManager.GetString("paypalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you should pay this product first.
        /// </summary>
        public static string payProductFirstMsg {
            get {
                return ResourceManager.GetString("payProductFirstMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string personalInformation {
            get {
                return ResourceManager.GetString("personalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pieces in store.
        /// </summary>
        public static string piecesInStore {
            get {
                return ResourceManager.GetString("piecesInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product Category.
        /// </summary>
        public static string productCategryPlaceholder {
            get {
                return ResourceManager.GetString("productCategryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Product Description here.
        /// </summary>
        public static string productDescriptionPlacholder {
            get {
                return ResourceManager.GetString("productDescriptionPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Product Name here.
        /// </summary>
        public static string productNamePlacholder {
            get {
                return ResourceManager.GetString("productNamePlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Number of units in store.
        /// </summary>
        public static string productNumberLabel {
            get {
                return ResourceManager.GetString("productNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Product Price in.
        /// </summary>
        public static string productPriceLabel {
            get {
                return ResourceManager.GetString("productPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Reviews.
        /// </summary>
        public static string productReviews {
            get {
                return ResourceManager.GetString("productReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we accept only &quot;gmail, yahoo, outlook, hotmail&quot;, you should use one of them.
        /// </summary>
        public static string realEmailErrMsg {
            get {
                return ResourceManager.GetString("realEmailErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string registerAsNewUser {
            get {
                return ResourceManager.GetString("registerAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string removeAll {
            get {
                return ResourceManager.GetString("removeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be careful you are going to Remove this Category for ever you cannot go back. if category have 1 or more product this action going to cancel.
        /// </summary>
        public static string removeCategoryWarningMsg {
            get {
                return ResourceManager.GetString("removeCategoryWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Admins.
        /// </summary>
        public static string removeFromAdmins {
            get {
                return ResourceManager.GetString("removeFromAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Favorite.
        /// </summary>
        public static string removeFromFavorite {
            get {
                return ResourceManager.GetString("removeFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Sellers.
        /// </summary>
        public static string removeFromSellers {
            get {
                return ResourceManager.GetString("removeFromSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Shipping Staff.
        /// </summary>
        public static string removeFromShippingStaff {
            get {
                return ResourceManager.GetString("removeFromShippingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Super Admins.
        /// </summary>
        public static string removeFromSuperAdmins {
            get {
                return ResourceManager.GetString("removeFromSuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this faild is required.
        /// </summary>
        public static string requiredMsg {
            get {
                return ResourceManager.GetString("requiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  you should choose Payment Method to compelete your order.
        /// </summary>
        public static string requiredPaymentMethod {
            get {
                return ResourceManager.GetString("requiredPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should choose one of this Methods to compelete your Order.
        /// </summary>
        public static string requiredPaymentMethodMsg {
            get {
                return ResourceManager.GetString("requiredPaymentMethodMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You shoud choose stars first.
        /// </summary>
        public static string requiredStarsMsg {
            get {
                return ResourceManager.GetString("requiredStarsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string resetPasswordConfirmation {
            get {
                return ResourceManager.GetString("resetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write your review here.
        /// </summary>
        public static string reviewDescriptionPlacholder {
            get {
                return ResourceManager.GetString("reviewDescriptionPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search about Your Product.
        /// </summary>
        public static string searchPlaceholder {
            get {
                return ResourceManager.GetString("searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string searchResult {
            get {
                return ResourceManager.GetString("searchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see all.
        /// </summary>
        public static string seeAll {
            get {
                return ResourceManager.GetString("seeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers.
        /// </summary>
        public static string sellers {
            get {
                return ResourceManager.GetString("sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me Link.
        /// </summary>
        public static string sendMeLink {
            get {
                return ResourceManager.GetString("sendMeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set Dark Mode.
        /// </summary>
        public static string setDarkMode {
            get {
                return ResourceManager.GetString("setDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set Light Mode.
        /// </summary>
        public static string setLightMode {
            get {
                return ResourceManager.GetString("setLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this product.
        /// </summary>
        public static string shareThisProduct {
            get {
                return ResourceManager.GetString("shareThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string shipping {
            get {
                return ResourceManager.GetString("shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Amount.
        /// </summary>
        public static string shippingAmount {
            get {
                return ResourceManager.GetString("shippingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Fee.
        /// </summary>
        public static string shippingFee {
            get {
                return ResourceManager.GetString("shippingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is all about shipping Fee Value.
        /// </summary>
        public static string shippingFeeFormMsg {
            get {
                return ResourceManager.GetString("shippingFeeFormMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Order.
        /// </summary>
        public static string shippingOrder {
            get {
                return ResourceManager.GetString("shippingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Staff.
        /// </summary>
        public static string shippingStaff {
            get {
                return ResourceManager.GetString("shippingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string shoppingCart {
            get {
                return ResourceManager.GetString("shoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Shopping and choose your items.
        /// </summary>
        public static string shoppingCartNoItemsMsg {
            get {
                return ResourceManager.GetString("shoppingCartNoItemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Slider.
        /// </summary>
        public static string showInSlider {
            get {
                return ResourceManager.GetString("showInSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Date.
        /// </summary>
        public static string signDate {
            get {
                return ResourceManager.GetString("signDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want to add this product you need to sign in first.
        /// </summary>
        public static string signToAddProduct {
            get {
                return ResourceManager.GetString("signToAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Setting.
        /// </summary>
        public static string siteSetting {
            get {
                return ResourceManager.GetString("siteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Statistics.
        /// </summary>
        public static string siteStatistics {
            get {
                return ResourceManager.GetString("siteStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we dont find any thing yet.
        /// </summary>
        public static string sorryMsg {
            get {
                return ResourceManager.GetString("sorryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Users.
        /// </summary>
        public static string sortUsers {
            get {
                return ResourceManager.GetString("sortUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your chars should be between 200 and 1000.
        /// </summary>
        public static string stringLength200_1000 {
            get {
                return ResourceManager.GetString("stringLength200_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your chars should be between 2050 and 500.
        /// </summary>
        public static string stringLength250_500 {
            get {
                return ResourceManager.GetString("stringLength250_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your chars should be between 3 and 200.
        /// </summary>
        public static string stringLength3_200 {
            get {
                return ResourceManager.GetString("stringLength3_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your chars should be between 3 and 200.
        /// </summary>
        public static string stringLength3_500 {
            get {
                return ResourceManager.GetString("stringLength3_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your chars should be between 4 and 60.
        /// </summary>
        public static string stringLength4_60 {
            get {
                return ResourceManager.GetString("stringLength4_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email confirmed Successfully . Please.
        /// </summary>
        public static string successConfirmEmail {
            get {
                return ResourceManager.GetString("successConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string successResetPasswordMsg {
            get {
                return ResourceManager.GetString("successResetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admins.
        /// </summary>
        public static string superAdmins {
            get {
                return ResourceManager.GetString("superAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Kushk company we have a team of shipping stuff they working so hard to get your products in time.
        /// </summary>
        public static string supportDescription {
            get {
                return ResourceManager.GetString("supportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this product rated by.
        /// </summary>
        public static string thisProductRatedBy {
            get {
                return ResourceManager.GetString("thisProductRatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Selling Products.
        /// </summary>
        public static string topSellingProducts {
            get {
                return ResourceManager.GetString("topSellingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under processing.
        /// </summary>
        public static string underProcessing {
            get {
                return ResourceManager.GetString("underProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your new photo.
        /// </summary>
        public static string userImageLabel {
            get {
                return ResourceManager.GetString("userImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this faild accept only arabic and english charcters.
        /// </summary>
        public static string validInput {
            get {
                return ResourceManager.GetString("validInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Customer Feedback.
        /// </summary>
        public static string verifiedCustomerFeedback {
            get {
                return ResourceManager.GetString("verifiedCustomerFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verified rating.
        /// </summary>
        public static string verifiedRating {
            get {
                return ResourceManager.GetString("verifiedRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Card.
        /// </summary>
        public static string visaCard {
            get {
                return ResourceManager.GetString("visaCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visaCardDescription.
        /// </summary>
        public static string visaCardDescription {
            get {
                return ResourceManager.GetString("visaCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodafone Cash.
        /// </summary>
        public static string vodafoneCash {
            get {
                return ResourceManager.GetString("vodafoneCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want to do this you cant go back again.
        /// </summary>
        public static string warningMsg {
            get {
                return ResourceManager.GetString("warningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Us.
        /// </summary>
        public static string whyUs {
            get {
                return ResourceManager.GetString("whyUs", resourceCulture);
            }
        }
    }
}
